# Generated by Django 6.0.3 on 2026-05-27 22:54

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('services', 'Services'), ('blog', 'Blog')], max_length=20)),
                ('variant', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Site', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo')),
                ('navbar_variant', models.CharField(choices=[('nav_1', 'Simple Header with Pills'), ('nav_2', 'Centered Pills Only'), ('nav_3', 'Three-Column with CTA Buttons'), ('nav_4', 'Dark with Search'), ('nav_5', 'Two-Tier Dark and Light')], default='nav_1', max_length=20)),
                ('footer_variant', models.CharField(choices=[('footer_1', 'Logo Center with Nav'), ('footer_2', 'Brand Left, Social Right'), ('footer_3', 'Centered Minimal'), ('footer_4', 'Multi-Column Sections'), ('footer_5', 'Newsletter Signup')], default='footer_1', max_length=20)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copyright_text', models.CharField(blank=True, default='My Site. All rights reserved.', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('newsletter_enabled', models.BooleanField(default=False)),
                ('newsletter_heading', models.CharField(blank=True, default='Subscribe to our newsletter', max_length=100)),
                ('newsletter_blurb', models.CharField(blank=True, default="Monthly digest of what's new and exciting from us.", max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('primary', models.CharField(default='#0d6efd', max_length=7)),
                ('secondary', models.CharField(default='#6c757d', max_length=7)),
                ('success', models.CharField(default='#198754', max_length=7)),
                ('danger', models.CharField(default='#dc3545', max_length=7)),
                ('warning', models.CharField(default='#ffc107', max_length=7)),
                ('info', models.CharField(default='#0dcaf0', max_length=7)),
                ('body_bg', models.CharField(default='#ffffff', max_length=7)),
                ('body_color', models.CharField(default='#212529', max_length=7)),
                ('heading_color', models.CharField(blank=True, help_text='Optional. Leave blank to use body color.', max_length=7)),
                ('link_color', models.CharField(blank=True, help_text='Optional. Leave blank to use primary color.', max_length=7)),
                ('font_family', models.CharField(default='system-ui, -apple-system, "Segoe UI", Roboto, sans-serif', max_length=200)),
                ('heading_font_family', models.CharField(blank=True, help_text='Optional. Leave blank to match body font.', max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('text_block', 'Text Block'), ('image_grid', 'Image Grid'), ('feature_list', 'Feature List'), ('cta_banner', 'Call to Action Banner'), ('testimonials', 'Testimonials'), ('gallery', 'Image Gallery')], max_length=30)),
                ('layout', models.CharField(choices=[('layout_1', 'Layout 1'), ('layout_2', 'Layout 2'), ('layout_3', 'Layout 3')], default='layout_1', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.TextField(blank=True)),
                ('background_color', models.CharField(blank=True, default='', max_length=20)),
                ('primary_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.site'),
        ),
        migrations.AddField(
            model_name='site',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='core.theme'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('site', 'page_type')},
        ),
    ]
