# Generated by Django 6.0.3 on 2026-05-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text_block', 'Text Block'), ('image_grid', 'Image Grid'), ('feature_list', 'Feature List'), ('cta_banner', 'Call to Action Banner'), ('testimonials', 'Testimonials'), ('gallery', 'Image Gallery'), ('contact_form', 'Contact Form'), ('video_embed', 'Video Embed'), ('pricing_table', 'Pricing Table')], max_length=30),
        ),
    ]
