# Generated by Django 6.0.3 on 2026-05-28 00:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='og_description',
            field=models.TextField(blank=True, help_text='Social share description. Defaults to the site tagline if left blank.'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Social share image for this specific page. Falls back to the site-wide OG image.', max_length=255, null=True, verbose_name='og_image'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, help_text='Social share title. Defaults to the page title if left blank.', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Small icon shown in browser tabs. PNG recommended (at least 32x32 px).', max_length=255, null=True, verbose_name='favicon'),
        ),
        migrations.AddField(
            model_name='site',
            name='og_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Default social share image. Used for pages that do not set their own. Recommended size: 1200x630 px.', max_length=255, null=True, verbose_name='og_image'),
        ),
        migrations.AddField(
            model_name='site',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nAllow: /\nDisallow: /admin/', help_text='Content served at /robots.txt. The default allows all crawlers except the admin.'),
        ),
    ]
