# Generated by Django 6.0.3 on 2026-05-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_page_og_description_page_og_image_page_og_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
    ]
