# Generated by Django 6.0.3 on 2026-05-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_page_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'base_manager_name': 'objects', 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sectionitem',
            options={'base_manager_name': 'objects', 'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='section',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
