# Generated by Django 6.0.3 on 2026-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_section_options_alter_sectionitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
