# Generated by Django 6.0.3 on 2026-05-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_columns', to='core.site')),
            ],
            options={
                'ordering': ['order'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footercolumn')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_links', to='core.page')),
            ],
            options={
                'ordering': ['order'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text='External URL or path. Used only when no page is selected.', max_length=500)),
                ('is_button', models.BooleanField(default=False, help_text='Render as a call-to-action button instead of a plain link.')),
                ('open_new_tab', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_links', to='core.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navlink')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_links', to='core.site')),
            ],
            options={
                'ordering': ['order'],
                'base_manager_name': 'objects',
            },
        ),
    ]
