"""
Backfill navigation for existing sites.

Before this release the navbar/footer were auto-generated by looping over the
page list. Now they are explicit NavLink / FooterColumn / FooterLink rows. This
migration creates those rows from each site's currently-enabled pages so an
upgraded site keeps the exact navigation it had, and the new templates (which
loop over nav_links) render correctly.

Safe to run on a fresh DB too: if there are no pages, it does nothing.
"""
from django.db import migrations


def backfill_navigation(apps, schema_editor):
    Site = apps.get_model('core', 'Site')
    Page = apps.get_model('core', 'Page')
    NavLink = apps.get_model('core', 'NavLink')
    FooterColumn = apps.get_model('core', 'FooterColumn')
    FooterLink = apps.get_model('core', 'FooterLink')

    for site in Site.objects.all():
        # Skip sites that already have nav links (shouldn't happen on upgrade,
        # but keeps this idempotent).
        if NavLink.objects.filter(site=site).exists():
            continue

        pages = list(
            Page.objects.filter(site=site, is_enabled=True).order_by('order')
        )
        if not pages:
            continue

        for i, page in enumerate(pages):
            NavLink.objects.create(
                site=site,
                page=page,
                label=page.title or page.page_type.title(),
                order=i,
                is_visible=True,
            )

        if not FooterColumn.objects.filter(site=site).exists():
            col = FooterColumn.objects.create(site=site, heading='Navigate', order=0)
            for i, page in enumerate(pages):
                FooterLink.objects.create(
                    column=col,
                    page=page,
                    label=page.title or page.page_type.title(),
                    order=i,
                )


def reverse_noop(apps, schema_editor):
    # No reverse: removing backfilled links would be destructive. The rows are
    # ordinary data the user may have since edited.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_footercolumn_footerlink_navlink'),
    ]

    operations = [
        migrations.RunPython(backfill_navigation, reverse_noop),
    ]
