# Generated by Django 6.0.3 on 2026-05-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backfill_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlink',
            name='slot',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Where this link sits in the navbar.', max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='brand_position',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Where the logo and/or site name appear in the navbar.', max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='show_brand_logo',
            field=models.BooleanField(default=True, help_text='Show the logo image in the navbar (if a logo is uploaded).'),
        ),
        migrations.AddField(
            model_name='site',
            name='show_brand_name',
            field=models.BooleanField(default=True, help_text='Show the site name text in the navbar.'),
        ),
    ]
