# Generated by CBL universal navbar update.
from django.db import migrations, models


def migrate_old_navbar_variants(apps, schema_editor):
    Site = apps.get_model('core', 'Site')
    mapping = {
        'nav_1': 'classic',
        'nav_2': 'centered',
        'nav_3': 'app',
        'nav_4': 'dark',
        'nav_5': 'split',
    }
    for site in Site.objects.all():
        new_value = mapping.get(site.navbar_variant)
        if new_value:
            site.navbar_variant = new_value
            site.save(update_fields=['navbar_variant'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_navlink_slot_site_brand_position_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_old_navbar_variants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='site',
            name='navbar_variant',
            field=models.CharField(
                choices=[
                    ('classic', 'Classic Business'),
                    ('centered', 'Centered Brand'),
                    ('app', 'App Style'),
                    ('dark', 'Dark Header'),
                    ('split', 'Split Navigation'),
                ],
                default='classic',
                help_text='Navbar preset. Presets change settings only; all presets use the same universal navbar engine.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='site',
            name='navbar_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('primary', 'Primary Brand Color'), ('transparent', 'Transparent')], default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='navbar_container',
            field=models.CharField(choices=[('container', 'Contained'), ('container-fluid', 'Full width')], default='container', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='navbar_sticky',
            field=models.BooleanField(default=False, help_text='Stick the navbar to the top while scrolling.'),
        ),
        migrations.AddField(
            model_name='site',
            name='navbar_shadow',
            field=models.BooleanField(default=True, help_text='Add a subtle border/shadow below the navbar.'),
        ),
        migrations.AddField(
            model_name='site',
            name='show_nav_search',
            field=models.BooleanField(default=False, help_text='Show a search form in the navbar.'),
        ),
        migrations.AddField(
            model_name='site',
            name='nav_search_slot',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='right', max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='show_nav_login',
            field=models.BooleanField(default=True, help_text='Show login link when visitors are signed out.'),
        ),
        migrations.AddField(
            model_name='site',
            name='show_nav_register',
            field=models.BooleanField(default=False, help_text='Show register/signup link when visitors are signed out.'),
        ),
        migrations.AddField(
            model_name='site',
            name='show_nav_profile',
            field=models.BooleanField(default=True, help_text='Show profile dropdown when users are signed in.'),
        ),
        migrations.AddField(
            model_name='site',
            name='nav_auth_slot',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='right', max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='nav_cta_label',
            field=models.CharField(blank=True, default='', help_text='Optional standalone CTA button label.', max_length=80),
        ),
        migrations.AddField(
            model_name='site',
            name='nav_cta_url',
            field=models.CharField(blank=True, default='', help_text='Optional standalone CTA button URL or path.', max_length=500),
        ),
        migrations.AddField(
            model_name='site',
            name='nav_cta_slot',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='right', max_length=10),
        ),
    ]
