# Generated by Django 6.0.3 on 2026-05-29 10:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_site_navbar_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='navbar_config',
            field=models.JSONField(blank=True, default=core.models.default_navbar_config, help_text='Advanced navbar layout/style controls (v1).'),
        ),
    ]
