# Generated by Django 6.0.3 on 2026-05-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_site_navbar_config'),
        ('core', '0012_site_show_navbar_footer'),
    ]

    operations = [
    ]
