# Generated by Django 6.0.3 on 2026-05-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_page_theme_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('recipient', models.EmailField(blank=True, default='', help_text='The address this submission was emailed to (from the section config).', max_length=254)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether the outbound notification email was sent successfully.')),
                ('is_read', models.BooleanField(default=False)),
                ('client_ip', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_submissions', to='core.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
