# Generated by Django 6.0.3 on 2026-05-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='active_pack_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
