# Generated by Django 6.0.3 on 2026-06-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='stripe_secret_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
