# Generated by Django 6.0.3 on 2026-06-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_stripe_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('services', 'Services'), ('blog', 'Blog'), ('ecommerce', 'Shop')], max_length=20),
        ),
    ]
