# Generated by Django 6.0.3 on 2026-06-01 02:42

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_recent_posts_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text_block', 'Text Block'), ('image_grid', 'Image Grid'), ('feature_list', 'Feature List'), ('cta_banner', 'Call to Action Banner'), ('testimonials', 'Testimonials'), ('gallery', 'Image Gallery'), ('contact_form', 'Contact Form'), ('video_embed', 'Video Embed'), ('pricing_table', 'Pricing Table'), ('recent_posts', 'Recent Blog Posts'), ('product_grid', 'Product Grid')], max_length=30),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=300, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('line_items', models.JSONField(default=list, help_text='Snapshot of purchased items.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in dollars (e.g. 9.99)', max_digits=10)),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited stock.', null=True)),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='featured_image')),
                ('is_active', models.BooleanField(default=True, help_text='Visible and purchasable on the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
