# Generated by Django 6.0.3 on 2026-06-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ecommerce'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='link_style',
            field=models.CharField(blank=True, default='', help_text='Bootstrap button class, e.g. btn-primary or btn-outline-secondary. Leave blank for default.', max_length=80),
        ),
    ]
