# Generated by Django 6.0.3 on 2026-06-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sectionitem_link_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='link_config',
            field=models.JSONField(blank=True, default=dict, help_text='Button appearance options: size, shape, shadow, hover, width.'),
        ),
    ]
