# Generated by Django 6.0.3 on 2026-06-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sectionitem_link_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlink',
            name='margin_left',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navlink',
            name='margin_right',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
