# Generated by Django 6.0.3 on 2026-06-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_navlink_margins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('above_navbar', 'Above navbar'), ('below_navbar', 'Below navbar')], default='above_navbar', max_length=20)),
                ('message', models.CharField(help_text='The banner text.', max_length=300)),
                ('link_text', models.CharField(blank=True, default='', help_text='Optional call-to-action label.', max_length=80)),
                ('link_url', models.CharField(blank=True, default='', help_text='Where the CTA / banner links to.', max_length=500)),
                ('bg_color', models.CharField(blank=True, default='', help_text='Background color (hex or CSS). Blank = brand color.', max_length=30)),
                ('text_color', models.CharField(blank=True, default='', help_text='Text color. Blank = white.', max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('dismissible', models.BooleanField(default=False, help_text='Let visitors close the banner.')),
                ('display_mode', models.CharField(choices=[('all', 'All pages'), ('selected', 'Only selected pages')], default='all', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pages', models.ManyToManyField(blank=True, help_text='Pages this banner shows on (when "Only selected pages" is chosen).', related_name='banners', to='core.page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='core.site')),
            ],
            options={
                'ordering': ['position', 'order', 'id'],
            },
        ),
    ]
