# Generated by Django 6.0.3 on 2026-06-02 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='install_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
