# Generated by Django 6.0.3 on 2026-06-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_site_install_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='license_key',
            field=models.CharField(blank=True, default='', help_text='Your purchase license key (from your receipt).', max_length=200),
        ),
    ]
