# Generated by Django 6.0.3 on 2026-06-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_site_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='item_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
