# Generated by Django 6.0.3 on 2026-06-02 21:51

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_sectionitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text_block', 'Text Block'), ('image_grid', 'Image Grid'), ('feature_list', 'Feature List'), ('cta_banner', 'Call to Action Banner'), ('testimonials', 'Testimonials'), ('gallery', 'Image Gallery'), ('contact_form', 'Contact Form'), ('video_embed', 'Video Embed'), ('pricing_table', 'Pricing Table'), ('recent_posts', 'Recent Blog Posts'), ('product_grid', 'Product Grid'), ('plan_grid', 'Plans / Projects Grid')], max_length=30),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Plan header — e.g. a job number or project name.', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional longer description shown on the detail page.')),
                ('specs', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.site')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.plan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
