# Generated by Django 6.0.3 on 2026-06-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_plans_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='body_end_html',
            field=models.TextField(blank=True, default='', help_text='Code added just before </body> on every page — deferred scripts, chat widgets, pixels that load late.'),
        ),
        migrations.AddField(
            model_name='site',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS applied site-wide. Do not include <style> tags — just the CSS rules.'),
        ),
        migrations.AddField(
            model_name='site',
            name='head_html',
            field=models.TextField(blank=True, default='', help_text='Code added inside <head> on every page — analytics tags, verification meta tags, fonts. Paste exactly what your provider gives you.'),
        ),
    ]
