# Generated by Django 6.0.3 on 2026-06-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_site_body_end_html_site_custom_css_site_head_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='Alt text for the featured image (accessibility + SEO). Defaults to the post title.', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Canonical URL for this page (advanced SEO). Leave blank to use this page's own address."),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Browser tab / search-result title for this page. Defaults to the page title if left blank.', max_length=200),
        ),
        migrations.AddField(
            model_name='planimage',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='Alt text for accessibility + SEO. Defaults to the plan title.', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='Alt text for the product image (accessibility + SEO). Defaults to the product name.', max_length=200),
        ),
        migrations.AddField(
            model_name='section',
            name='anchor_id',
            field=models.SlugField(blank=True, default='', help_text='Optional anchor for in-page links. E.g. "pricing" lets you link to #pricing.', max_length=60),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='Describes the image for screen readers and search engines. Leave blank for decorative images.', max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text_block', 'Text Block'), ('image_grid', 'Image Grid'), ('feature_list', 'Feature List'), ('cta_banner', 'Call to Action Banner'), ('testimonials', 'Testimonials'), ('gallery', 'Image Gallery'), ('contact_form', 'Contact Form'), ('video_embed', 'Video Embed'), ('pricing_table', 'Pricing Table'), ('recent_posts', 'Recent Blog Posts'), ('product_grid', 'Product Grid'), ('plan_grid', 'Plans / Projects Grid'), ('faq', 'FAQ / Accordion'), ('stats', 'Stats / Counters'), ('html_embed', 'Raw HTML Embed')], max_length=30),
        ),
    ]
