# Generated by Django 6.0.3 on 2026-06-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_blogpost_image_alt_page_canonical_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='CSS applied to this page only (no <style> tags).'),
        ),
        migrations.AddField(
            model_name='page',
            name='head_html',
            field=models.TextField(blank=True, default='', help_text='Code added inside <head> on this page only.'),
        ),
        migrations.AddField(
            model_name='page',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Optional: schedule this page to go live automatically at this date/time.', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='cookie_consent_button_text',
            field=models.CharField(blank=True, default='Got it', help_text='Dismiss button label.', max_length=40),
        ),
        migrations.AddField(
            model_name='site',
            name='cookie_consent_enabled',
            field=models.BooleanField(default=False, help_text='Show a cookie-consent banner until the visitor dismisses it.'),
        ),
        migrations.AddField(
            model_name='site',
            name='cookie_consent_text',
            field=models.CharField(blank=True, default='We use cookies to improve your experience. By using this site, you accept our use of cookies.', help_text='Message shown in the cookie banner.', max_length=300),
        ),
        migrations.AddField(
            model_name='site',
            name='error_404_message',
            field=models.TextField(blank=True, default="Sorry, we couldn't find the page you were looking for.", help_text='Message shown on the 404 page.'),
        ),
        migrations.AddField(
            model_name='site',
            name='error_404_title',
            field=models.CharField(blank=True, default='Page not found', help_text='Heading shown on the 404 (page not found) error page.', max_length=120),
        ),
        migrations.AddField(
            model_name='site',
            name='error_500_message',
            field=models.TextField(blank=True, default='An unexpected error occurred. Please try again in a moment.', help_text='Message shown on the 500 page.'),
        ),
        migrations.AddField(
            model_name='site',
            name='error_500_title',
            field=models.CharField(blank=True, default='Something went wrong', help_text='Heading shown on the 500 (server error) page.', max_length=120),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text_block', 'Text Block'), ('image_grid', 'Image Grid'), ('feature_list', 'Feature List'), ('cta_banner', 'Call to Action Banner'), ('testimonials', 'Testimonials'), ('gallery', 'Image Gallery'), ('contact_form', 'Contact Form'), ('video_embed', 'Video Embed'), ('pricing_table', 'Pricing Table'), ('recent_posts', 'Recent Blog Posts'), ('product_grid', 'Product Grid'), ('plan_grid', 'Plans / Projects Grid'), ('faq', 'FAQ / Accordion'), ('stats', 'Stats / Counters'), ('html_embed', 'Raw HTML Embed'), ('tabs', 'Tabs'), ('team', 'Team / Staff Bios'), ('logo_wall', 'Logo Wall'), ('timeline', 'Timeline'), ('map_embed', 'Map Embed'), ('code_block', 'Code Block')], max_length=30),
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(blank=True, default='', help_text='Where the signup came from (e.g. footer).', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscribers', to='core.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('site', 'email')},
            },
        ),
    ]
